### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by rafed** [SampadSikder/EnsembleLocator#5]
```First 10 lines of C:\Users\rafed\Desktop\EnsembleLocator\script\results\bug_100.xml\BugLocator_AspectJResult\recommended\279120.txt:
0       1.0     weaver/src/org/aspectj/weaver/tools/WeavingAdaptor.java
1       0.9342051       weaver/src/org/aspectj/weaver/bcel/BcelObjectType.java
2       0.8698186       loadtime5/java5-src/org/aspectj/weaver/loadtime/Agent.java
3       0.8370266       loadtime/src/org/aspectj/weaver/loadtime/ClassLoaderWeavingAdaptor.java
4       0.7998018       weaver/src/org/aspectj/weaver/bcel/BcelMethod.java
5       0.77813536      weaver/src/org/aspectj/weaver/bcel/BcelWeaver.java
6       0.72247744      org.aspectj.ajdt.core/testsrc/org/aspectj/tools/ajc/AjcTestCase.java
7       0.7004284       weaver5/java5-testsrc/org/aspectj/weaver/tools/Java15PointcutExpressionTest.java
8       0.6794738       weaver/src/org/aspectj/weaver/bcel/AtAjAttributes.java
9       0.67668384      org.aspectj.ajdt.core/testsrc/org/aspectj/ajdt/internal/compiler/batch/BcweaverJarMaker.java
Error: could not find change level oracles
error happens when writing lines to file null
java.lang.NullPointerException
        at java.base/java.io.File.<init>(File.java:278)
        at utils.WriteLinesToFile.writeLinesToFile(WriteLinesToFile.java:11)
        at miningChanges.ProduceFileLevelResults.integrateResults(ProduceFileLevelResults.java:345)
        at miningChanges.ProduceFileLevelResults.getFinalResults(ProduceFileLevelResults.java:380)
        at main.Main.startTask(Main.java:57)
        at main.Main.main(Main.java:195)
```

**Comment by SampadSikder** [comment]
Null pointer exception occurs as Locus could not generate folders previously. Also, parser of Locus parses XML differently than other methods. So Locus input has been differentiated from the inputs of other techniques. This has been fixed now
