### ISSUE TITLE
Error executing BLUiR

### ISSUE THREAD

**Issue by rafed** [SampadSikder/EnsembleLocator#6]
```
Error executing BLUiR: Command failed: java -jar C:\Users\rafed\Desktop\EnsembleLocator\BLUiR_jar\BLUiR.jar -b C:\Users\rafed\Desktop\EnsembleLocator\script\BugReports\bug_100.xml -s C:\Users\rafed\Desktop\mfejzer\tracking_buggy_files_aspectj_dataset -a 0.3 -w C:\Users\rafed\Desktop\EnsembleLocator\script\results\bug_100.xml -n AspectJResult
Cannot load Settings.txt File. Please let the file locate root path.
Exception in thread "main" java.lang.NullPointerException: Cannot read field "WorkDir" because the return value of "bluir.core.Property.getInstance()" is null 
        at bluir.core.Core.<init>(Core.java:15)
        at bluir.core.BLUiR.main(BLUiR.java:32)

Error executing command for bug_100.xml: Error: Command failed: java -jar C:\Users\rafed\Desktop\EnsembleLocator\BLUiR_jar\BLUiR.jar -b C:\Users\rafed\Desktop\EnsembleLocator\script\BugReports\bug_100.xml -s C:\Users\rafed\Desktop\mfejzer\tracking_buggy_files_aspectj_dataset -a 0.3 -w C:\Users\rafed\Desktop\EnsembleLocator\script\results\bug_100.xml -n AspectJResult
Cannot load Settings.txt File. Please let the file locate root path.
Exception in thread "main" java.lang.NullPointerException: Cannot read field "WorkDir" because the return value of "bluir.core.Property.getInstance()" is null 
        at bluir.core.Core.<init>(Core.java:15)
        at bluir.core.BLUiR.main(BLUiR.java:32)

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'java -jar C:\\Users\\rafed\\Desktop\\EnsembleLocator\\BLUiR_jar\\BLUiR.jar -b C:\\Users\\rafed\\Desktop\\EnsembleLocator\\script\\BugReports\\bug_100.xml -s C:\\Users\\rafed\\Desktop\\mfejzer\\tracking_buggy_files_aspectj_dataset -a 0.3 -w C:\\Users\\rafed\\Desktop\\EnsembleLocator\\script\\results\\bug_100.xml -n AspectJResult'
}
```

**Comment by SampadSikder** [comment]
- Was failing due to the absence of Settings file. Settings file has now been added to repo
